blog/urls.py
from django.urls import path
from blog.views import add_post, add_theme, home, post, theme, search_result



app_name='blog'
urlpatterns=[
	path('', home, name='home'),
	path('post-<int:pk>/', post, name="post"),
	path('theme-<int:pk>/', theme, name="theme"),
	path('add/', add_post, name="add"),
	path('adtheme/', add_theme, name="adtheme"),
	path('search_result/', search_result, name="search_result")
]

blog/models.py
from django.db import models
class Theme(models.Model):

	title = models.CharField(max_length=128)
	color = models.CharField(max_length=8)
	image = models.ImageField(upload_to='uploads/')
	
	def __str__(self):
		return self.title
	
class Post(models.Model):
	title = models.CharField(max_length=128)
	content = models.TextField()
	add_time = models.DateTimeField(auto_now_add=True)
	theme=models.ForeignKey(
		Theme, 
		on_delete=models.CASCADE,
		null=True
	)
	
	def __str__(self):
		return self.title

blog/forms.py
from django import forms
from blog.models import Post, Theme

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields=['theme','title','content']

class ThemeForm(forms.ModelForm):
	class Meta:
		model = Theme
		fields=['title','color','image']

blog/views.py
from functools import reduce
import operator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Q
from blog.models import Post, Theme
from blog.forms import PostForm, ThemeForm

def home(request):
	posts=Post.objects.all()
	return render(request, 'articles/home.html',{
		'posts':posts
	})
	
	
def post(request, pk):
	blog_post=Post.objects.get(id=pk)
	# Post.objects.filter()
	return  render(request, 'articles/post.html',{
		'post':blog_post
	})
	
def theme(request, pk):

	blog_theme=Theme.objects.get(id=pk)
	posts=Post.objects.filter(theme=blog_theme)
	
	return  render(request, 'articles/home.html',{
		'posts':posts
	})
	
	
def add_post(request):
	if request.method=='POST':
		form=PostForm(request.POST)
		
		if form.is_valid():
			form.save()
			return redirect(reverse('blog:home'))
	else:
		form=PostForm()
	
	
	return  render(request, 'articles/add_post.html',{
		'form':form
	})
	
def add_theme(request):
	if request.method=='POST':
		form=ThemeForm(request.POST,request.FILES)
		
		if form.is_valid():
			form.save()
			return redirect(reverse('blog:home'))
	else:
		form=ThemeForm()
	
	
	return  render(request, 'articles/add_theme.html',{
		'form':form
	})
	
def search_result(request):
	q=request.GET.get('q')
	use_content=request.GET.get('content')
	fltr=request.GET.get('find')
	# if use_content:
		# posts=Post.objects.filter(
			# Q(title__icontains=q)| Q(content__icontains=q)
		# )
	# else:
		# posts=Post.objects.filter(title__icontains=q)
	# query = [Q(title__icontains=q)]
	
	# if use_content:
		# query.append(Q(content__icontains=q))
	
		# posts=Post.objects.filter(reduce(operator.or_, query))
		
	# return render(request, 'articles/home.html', {
		# 'posts':posts,
		# 'q':q
		# })
			
	if (fltr=='all'):
		if use_content:
			posts=Post.objects.filter(
				Q(title__icontains=q)| Q(content__icontains=q)
			)
		else:
			posts=Post.objects.filter(title__icontains=q)
			
		return render(request, 'articles/home.html', {
			'posts':posts,
			'q':q
			})
	elif (fltr=='ex'):
		if use_content:
			posts=Post.objects.filter(
				Q(title__iexact=q)| Q(content__iexact=q)
			)
		else:
			posts=Post.objects.filter(title__iexact=q)
		return render(request, 'articles/home.html', {
			'posts':posts,
			'q':q,
				
			})
	elif (fltr=='st'):
		if use_content:
			posts=Post.objects.filter(
				Q(title__istartswith=q)| Q(content__istartswith=q)
			)
		else:
			posts=Post.objects.filter(title__istartswith=q)
		return render(request, 'articles/home.html', {
			'posts':posts,
			'q':q,
				
			})
	elif (fltr=='en'):
		if use_content:
			posts=Post.objects.filter(
				Q(title__iendswith=q)| Q(content__iendswith=q)
			)
		else:
			posts=Post.objects.filter(title__iendswith=q)
		return render(request, 'articles/home.html', {
			'posts':posts,
			'q':q,
		
			})
	 	

blog/templates/articles/add_post.html
<h1>Add post</h1>
<form action="" method="post">
{{form.as_p}}
<div>
	{% csrf_token %}
	<button type="submit">Save</button>
</div>
</form>

blog/templates/articles/add_theme.html
<h1>Add theme</h1>
<form action="" method="post" enctype="multipart/form-data">
{{form.as_p}}
<div>
	{% csrf_token %}
	<button type="submit">Save</button>
</div>
</form>

blog/templates/articles/home.html
<div>
	<a href="{% url 'blog:add' %}">Добавить Пост</a>
	<a href="{% url 'blog:adtheme' %}">Добавить Тему</a>
	
</div>


<div>
<form action="{%url 'blog:search_result'%}">
				<select name="find">
					<option value="all">all</option>
					<option value="ex">exact</option>
					<option value="st">starts with</option>
					<option value="en">ends with</option>
			</select>
				
				<input type="text" name="q" placeholder="Search String" value="{{q}}">
				<button type="submit">SEARCH</button>
				<label for="">
				<input type="checkbox" name="content" value="1">
					search in content
				</label>
</form>

	{% for post in posts %}
		<div>
			<h1>
				<a href="/blog/theme-{{post.theme.id}}/">{{post.theme}}</a>
			</h1>
			<img src="{{ post.theme.image.url }}" height="40px">
			<h3>
				---->><a href="/blog/post-{{post.id}}/">{{post.title}}</a>
			</h3>
			
			<!-- <p> -->
				<!-- {{post.content}} -->
			<!-- </p> -->
			<!-- <p> -->
				<!-- {{post.add_time}} -->
			<!-- </p> -->
			<!-- <div>{{post.theme}}</div> -->
		</div>
	{%endfor%}
</div>

blog/templates/articles/post.html
<h1>{{post.title}}</h1>
<div>{{post.content}}</div>
<div>{{post.add_time}}</div>